#!/usr/bin/env bash

APP="dand" # name of your release

BUILD_HOST="dnd.nmq.digital" # host where to build the release
BUILD_USER="istateasedev" # local user at build host
BUILD_AT="/var/www/apps/dand/builds" # build directory on build host

PRODUCTION_HOSTS="dnd.nmq.digital" # deploy / production hosts separated by space
PRODUCTION_USER="istateasedev" # local user at deploy hosts
DELIVER_TO="/var/www/apps/dand/app_release" # deploy directory on production hosts

pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/var/www/apps/dand/app_config/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}

pre_erlang_clean_compile() {
  status "Preparing assets with: brunch build and phx.digest"
  __sync_remote "
    # runs the commands on the build host
    # [ -f ~/.profile ] && source ~/.profile # load profile (optional)

    # fail if any command fails (recommended)
    set -e

    # enter the build directory on the build host (required)
    cd '$BUILD_AT'

    mkdir -p priv/static # required by the phoenix.digest task

    # installing npm dependencies & building brunch
    cd assets && npm install

    brunch build --production

    # Back to app folder
    cd '$BUILD_AT'

    # run your custom task

    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phx.digest $SILENCE
  "
} 
