#!/usr/bin/env bash

APP="dand" # name of your release

BUILD_HOST="dnd.nmq.digital" # host where to build the release
BUILD_USER="istateasedev" # local user at build host
BUILD_AT="/var/www/apps/dand/builds" # build directory on build host

PRODUCTION_HOSTS="dnd.nmq.digital" # deploy / production hosts separated by space
PRODUCTION_USER="istateasedev" # local user at deploy hosts
DELIVER_TO="/var/www/apps/dand/app_release" # deploy directory on production hosts

pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/var/www/apps/dand/app_config/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}
