#!/usr/bin/env bash

APP="dand" # name of your release
VERSION="0.0.1"
BUILD_HOST="dnd.nmq.digital" 
BUILD_USER="istateasedev" 
BUILD_AT="/tmp/edeliver/$APP/builds"

RELEASE_DIR="/tmp/edeliver/$APP/builds/_build/prod/rel/$APP"

PRODUCTION_HOSTS="dnd.nmq.digital" # deploy / production hosts separated by space
PRODUCTION_USER="istateasedev" # local user at deploy hosts
DELIVER_TO="/var/www/apps/" # deploy directory on production hosts

GIT_CLEAN_PATHS="_build rel priv/static"

pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/var/www/apps/dand/app_config/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}

pre_erlang_clean_compile() {
  status "Preparing assets with: brunch build and phx.digest"
  __sync_remote "
    set -e
    cd '$BUILD_AT'
    mkdir -p priv/static
    cd assets && npm install && brunch build --production
    cd '$BUILD_AT'
    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phx.digest $SILENCE
  "
} 
